project_id = "wbnrmnfsxrxcxnvmowtp"

[functions.populate-program-templates]
verify_jwt = false

[functions.warden-tts]
verify_jwt = false

[functions.email-subscribe]
verify_jwt = false

[functions.generate-onboarding-script]
verify_jwt = false

[functions.generate-onboarding-audio]
verify_jwt = false

[functions.tier-onboarding-generate]
verify_jwt = false

[functions.update-to-dom-style]
verify_jwt = false
